// GENERATED by scripts/generate-emoji-catalog.mjs --manifest. Do not edit; regenerate.
// Design: ink://designs/reaction-emoji-catalog §1. The Inkling app copies each
// file below byte for byte; both repos check these hashes and the digest.

export const EMOJI_PARITY_MANIFEST_VERSION = 1;

/** Each copied module, by path under stories/, with its SHA-256. */
export const EMOJI_PARITY_FILES: ReadonlyArray<readonly [string, string]> = [
  ["reacting/index.ts", "917daf879cb7736abce63eda24da871565f94ffacd578391d427cb3eb991ac6f"],
  ["reacting/normalize.ts", "e733442ce434efd31bf328dba98fa9ac4d2d063e1e776c3168e5d4c364aed8a3"],
  ["reacting/validation.generated.ts", "c1a56ee35bd89616fbb6175cc9f78b0e8f16b593f227c9bb4f0e0698f002fbb2"],
  ["reaction-picking/index.ts", "8e11db8fead6647235c86e25264cb668635199c0e1cd6ef974ff884209037da6"],
  ["reaction-picking/parity-vectors.ts", "512300d23d19e4d5cb25286f934e79800696445a8c824ff85c6fe1aced79f437"],
  ["reaction-picking/search-aliases.ts", "035aad62d163fe6e570392667ad63bfe8ffcce1e4dddfc50470545b39111cc1c"],
  ["reaction-picking/search.generated.ts", "d0e0d58ec0885050f6cb03002248f48764cb1d5f071ba9deab9ee09c15318eee"],
  ["reaction-picking/search.ts", "47eaf592ee2f2277e1e417fd2ed9252620e617cebf27c410004152c0ec100b88"],
];

/** SHA-256 over "<path>\t<sha256>\n" for each file above, sorted by path. */
export const EMOJI_PARITY_DIGEST = "3b3c290d42bca4d20501816a727b72e324a25173ecbd7506aece4837ac18f119";
