/** Compatibility path; the shared runtime owns the implementation. */
export {
  createSignalSink,
  CLIENT_LOCAL_TOOLS,
  isClientLocalTool,
  effectiveContextTokens,
  computeContextOccupancy,
  formatContextStamp,
  handleClientLocalTool,
  COMPACT_CONTEXT_SUMMARY_MAX_CHARS,
  COMPACT_CONTEXT_MAX_KEEP_RECENT,
  COMPACT_CONTEXT_MAX_REFS,
  compactionShrinks,
  parseCompactContextArgs,
  LIST_CONTEXT_DEFAULT_LIMIT,
  LIST_CONTEXT_BOOKMARK_LIMIT,
  LIST_CONTEXT_MAX_LIMIT,
  EVICT_CONTEXT_PREVIEW_LIMIT,
  type SessionStatus,
  type SessionSignal,
  type SignalSink,
  type SessionSignalState,
  type ContextToolResult,
  type EvictRef,
  type EvictionHooks,
  type ProviderContextMeasurement,
  type ContextOccupancy,
  type CompactContextArgs,
} from '@inklabs/shared/runtime';
