/** Compatibility path for shared clone admission and validation. */
export {
  SPAWN_AGENT_TOOL,
  COLLECT_AGENTS_TOOL,
  isCloneHandoffTool,
  MAX_CLONES_PER_SPAWN,
  type SpawnAgentTask,
  type SpawnAgentRequest,
  type SpawnAgentParse,
  parseSpawnAgentArgs,
  type SpawnAdmission,
  admitSpawn,
  type IterationScreen,
  screenIteration,
  buildClonePrompt,
  boundSummary,
  describeCloneToolResult,
  classifyCloneOutcome,
  MAX_CLONE_SUMMARY_CHARS,
  formatFanOutForLedger,
  selectOutcomesToLedger,
  type CloneOutcomeSummary,
} from '@inklabs/shared/runtime';
