import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { readCodexConfig, syncMcpConfig } from './mcp-config-sync.js';
import { readTomlDefinitions } from './toml-definitions.js';

let root: string;
beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'mcp-config-sync-'));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

const twoServers = {
  figma: { type: 'http', url: 'https://mcp.example.com/figma' },
  inkwell: { type: 'http', url: 'http://localhost:3001/mcp' },
};

function studio(codexToml?: string, servers: Record<string, unknown> = twoServers): string {
  writeFileSync(join(root, '.mcp.json'), JSON.stringify({ mcpServers: servers }));
  if (codexToml !== undefined) {
    mkdirSync(join(root, '.codex'));
    writeFileSync(join(root, '.codex', 'config.toml'), codexToml);
  }
  return join(root, '.codex', 'config.toml');
}

/** Whether the file defines `mcp_servers.<name>`, in any form, and never twice. */
function definedOnce(toml: string, name: string): boolean {
  const definitions = readTomlDefinitions(toml);
  return (
    !!definitions.definedBy(['mcp_servers', name]) &&
    !definitions.redefinitions.some(
      ({ path }) => path[0] === 'mcp_servers' && (path.length === 1 || path[1] === name)
    )
  );
}

/** The servers ink's managed block defines, in order. */
function blockServers(toml: string): string[] {
  const lines = toml.split('\n');
  const start = lines.indexOf('# ink-managed:start mcp_servers');
  const end = lines.indexOf('# ink-managed:end mcp_servers');
  return readTomlDefinitions(toml)
    .statements.filter(
      (s) =>
        s.kind === 'table' &&
        s.path[0] === 'mcp_servers' &&
        s.path.length === 2 &&
        s.line - 1 > start &&
        s.line - 1 < end
    )
    .map((s) => s.path[1]!);
}

/** What Codex would refuse or could not be read: nothing, for a file it parses. */
function parseProblems(toml: string) {
  const reading = readCodexConfig(toml);
  return { redefined: reading.redefined, unreadableLine: reading.unreadableLine };
}

describe("syncMcpConfig: lumen-alpha's config as found on 2026-09-29 (#701)", () => {
  // Line for line the skeleton of that file, values synthetic: the legacy
  // header on line 1, a hooks table whose start marker is gone, the managed
  // block on lines 10-35 holding figma at 14, and figma again at 37. Codex
  // refused it (duplicate key), so every spawn in that studio failed.
  const servers = {
    figma: { type: 'http', url: 'https://mcp.example.com/figma' },
    supabase: { type: 'http', url: 'https://mcp.example.com/supabase' },
    inkwell: { type: 'http', url: 'http://localhost:3001/mcp' },
    github: {
      type: 'http',
      url: 'https://mcp.example.com/github',
      headers: { Authorization: 'Bearer ${GITHUB_PAT}' },
    },
    inkmail: { command: 'node', args: ['inkmail.js'] },
    playwright: { command: 'npx', args: ['playwright-mcp'] },
  };
  const lumenAlpha = [
    '# Generated by `sb config sync` from .mcp.json',
    '# Re-run `sb config sync` after changing .mcp.json',
    '',
    '[hooks]',
    'session_start = "ink hooks on-session-start --backend codex"',
    'session_end = "ink hooks on-stop --backend codex"',
    'user_prompt = "ink hooks on-prompt --backend codex"',
    '# ink-managed:hooks:end',
    '',
    '# ink-managed:start mcp_servers',
    '# Generated by `ink mcp sync` from .mcp.json',
    '# Re-run `ink mcp sync` after changing .mcp.json',
    '',
    '[mcp_servers.figma]',
    'url = "https://mcp.example.com/figma"',
    '',
    '[mcp_servers.supabase]',
    'url = "https://mcp.example.com/supabase"',
    '',
    '[mcp_servers.inkwell]',
    'url = "http://localhost:3001/mcp"',
    'required = true',
    '',
    '[mcp_servers.github]',
    'url = "https://mcp.example.com/github"',
    'bearer_token_env_var = "GITHUB_PAT"',
    '',
    '[mcp_servers.inkmail]',
    'command = "node"',
    'args = ["inkmail.js"]',
    '',
    '[mcp_servers.playwright]',
    'command = "npx"',
    'args = ["playwright-mcp"]',
    '# ink-managed:end mcp_servers',
    '',
    '[mcp_servers.figma]',
    'url = "https://mcp.example.com/figma"',
    '',
  ].join('\n');

  it('is the file Codex refused: figma defined twice, once on each side of the block', () => {
    expect(lumenAlpha.split('\n')[13]).toBe('[mcp_servers.figma]');
    expect(lumenAlpha.split('\n')[36]).toBe('[mcp_servers.figma]');
    expect(readCodexConfig(lumenAlpha)).toMatchObject({
      redefined: ['mcp_servers.figma'],
      collidingWithBlock: ['figma'],
      redefinedOutsideBlock: [],
    });
  });

  it('comes out parsing, with one figma, kept where it was outside the block, and every other server in it', () => {
    const codexPath = studio(lumenAlpha, servers);
    const result = syncMcpConfig(root);
    const text = readFileSync(codexPath, 'utf-8');
    expect(parseProblems(text)).toEqual({ redefined: [], unreadableLine: undefined });
    for (const name of Object.keys(servers)) expect(definedOnce(text, name), name).toBe(true);
    expect(blockServers(text)).toEqual(['supabase', 'inkwell', 'github', 'inkmail', 'playwright']);
    expect(result.codexKeptOutside).toEqual(['figma']);
    expect(result.codexHandEdit).toBeUndefined();
    // Outside the block, byte for byte: the header, the hooks and figma's copy.
    expect(text.startsWith(lumenAlpha.split('# ink-managed:start')[0]!)).toBe(true);
    expect(text.endsWith(lumenAlpha.split('# ink-managed:end mcp_servers\n')[1]!)).toBe(true);
  });

  it('a second sync changes nothing', () => {
    const codexPath = studio(lumenAlpha, servers);
    syncMcpConfig(root);
    const once = readFileSync(codexPath, 'utf-8');
    syncMcpConfig(root);
    expect(readFileSync(codexPath, 'utf-8')).toBe(once);
  });
});

describe('syncMcpConfig: a server defined outside the block, in any spelling (Myra, #701 d0f4698e)', () => {
  const block = (...body: string[]) => [
    '# ink-managed:start mcp_servers',
    ...body,
    '# ink-managed:end mcp_servers',
  ];
  const inkwellOnly = ['[mcp_servers.inkwell]', 'url = "http://localhost:3001/mcp"'];
  const withFigma = [
    '[mcp_servers.figma]',
    'url = "https://mcp.example.com/figma"',
    ...inkwellOnly,
  ];

  // Every form that defines the table mcp_servers.figma itself (Myra, #701
  // 73a3b6fd), before or after the block as each one can be written.
  for (const [name, { before = [], after = [] }] of [
    [
      'a two-segment header, quoted and spaced',
      { after: ['[ mcp_servers . "figma" ]', 'url = "https://mcp.example.com/figma"'] },
    ],
    ['root dotted keys', { before: ['mcp_servers.figma.url = "https://mcp.example.com/figma"'] }],
    [
      'dotted keys under [mcp_servers]',
      { after: ['[mcp_servers]', 'figma.url = "https://mcp.example.com/figma"'] },
    ],
    [
      'an inline table under [mcp_servers]',
      { after: ['[mcp_servers]', 'figma = { url = "https://mcp.example.com/figma" }'] },
    ],
    [
      'a root inline table',
      { before: ['mcp_servers.figma = { url = "https://mcp.example.com/figma" }'] },
    ],
  ] as const) {
    const file = (body: readonly string[]) =>
      [...before, '', ...block(...body), ...after, ''].join('\n');

    it(`${name}: beside figma in the block it is a redefinition, and the sync leaves figma to it`, () => {
      expect(readCodexConfig(file(withFigma))).toMatchObject({
        redefined: ['mcp_servers.figma'],
        collidingWithBlock: ['figma'],
      });
      const codexPath = studio(file(inkwellOnly));
      const result = syncMcpConfig(root);
      const text = readFileSync(codexPath, 'utf-8');
      expect(parseProblems(text)).toEqual({ redefined: [], unreadableLine: undefined });
      expect(definedOnce(text, 'figma')).toBe(true);
      expect(blockServers(text)).toEqual(['inkwell']);
      expect(result.codexKeptOutside).toEqual(['figma']);
    });
  }

  it('a file with no block, whose old section the legacy strip does not recognise', () => {
    const codexPath = studio(
      ['[ mcp_servers . figma ]', 'url = "https://mcp.example.com/figma"', ''].join('\n')
    );
    const result = syncMcpConfig(root);
    const text = readFileSync(codexPath, 'utf-8');
    expect(parseProblems(text)).toEqual({ redefined: [], unreadableLine: undefined });
    expect(definedOnce(text, 'figma')).toBe(true);
    expect(blockServers(text)).toEqual(['inkwell']);
    expect(result.codexKeptOutside).toEqual(['figma']);
  });

  it('a sub-table outside, beside the server in the block, is no collision: the server stays in the block (control)', () => {
    const codexPath = studio(
      [...block(), '[mcp_servers.figma.http_headers]', 'X-Team = "design"', ''].join('\n')
    );
    const result = syncMcpConfig(root);
    const text = readFileSync(codexPath, 'utf-8');
    expect(parseProblems(text)).toEqual({ redefined: [], unreadableLine: undefined });
    expect(blockServers(text)).toEqual(['figma', 'inkwell']);
    expect(result).toEqual({ codex: true, gemini: true });
  });

  it('keeps every server in the block when none is defined outside, and reports nothing (control)', () => {
    const codexPath = studio();
    const result = syncMcpConfig(root);
    const text = readFileSync(codexPath, 'utf-8');
    expect(definedOnce(text, 'figma')).toBe(true);
    expect(definedOnce(text, 'inkwell')).toBe(true);
    expect(blockServers(text)).toEqual(['figma', 'inkwell']);
    expect(readCodexConfig(text)).toMatchObject({
      definesInkwell: true,
      inkwellOutsideBlock: false,
    });
    expect(result).toEqual({ codex: true, gemini: true });
  });
});

describe('syncMcpConfig: what it cannot repair, it names as a hand edit (Myra, #701 d0f4698e)', () => {
  it('inkwell defined outside the block: left there, and named, not repaired quietly', () => {
    const codexPath = studio(
      [
        '# ink-managed:start mcp_servers',
        '# ink-managed:end mcp_servers',
        '[mcp_servers.inkwell]',
        'url = "http://localhost:9999/stale"',
        '',
      ].join('\n')
    );
    const result = syncMcpConfig(root);
    const text = readFileSync(codexPath, 'utf-8');
    expect(parseProblems(text)).toEqual({ redefined: [], unreadableLine: undefined });
    expect(result.codexKeptOutside).toEqual(['inkwell']);
    expect(result.codexHandEdit).toEqual([
      ".codex/config.toml defines the inkwell server outside ink's managed block, where the sync cannot update it: remove that definition, then run `ink mcp sync`",
    ]);
    expect(readCodexConfig(text)).toMatchObject({
      definesInkwell: true,
      inkwellOutsideBlock: true,
    });
  });

  // What would be written is read before it is written; a file that fails
  // the reading is left as it was (Myra, #701 73a3b6fd).
  it('a table defined twice outside the block: named, and the file left unchanged', () => {
    const broken = ['[profiles.fast]', 'model = "m"', '[ profiles . "fast" ]', 'model = "m"', ''];
    const codexPath = studio(broken.join('\n'));
    const result = syncMcpConfig(root);
    expect(result).toEqual({
      codex: false,
      gemini: true,
      codexHandEdit: [
        ".codex/config.toml defines [profiles.fast] more than once outside ink's managed block, which Codex cannot parse, so the sync left it unchanged: remove one, then run `ink mcp sync`",
      ],
    });
    expect(readFileSync(codexPath, 'utf-8')).toBe(broken.join('\n'));
  });

  it('text it cannot read: named with its line, and the file left unchanged', () => {
    const unreadable = ['model = "gpt', '[mcp_servers.figma]', 'url = "x"', ''].join('\n');
    const codexPath = studio(unreadable);
    const result = syncMcpConfig(root);
    expect(result).toEqual({
      codex: false,
      gemini: true,
      codexHandEdit: [
        '.codex/config.toml could not be read at line 1, so the sync left it unchanged: fix that line, then run `ink mcp sync`',
      ],
    });
    expect(readFileSync(codexPath, 'utf-8')).toBe(unreadable);
  });
});
