/**
 * MCP Config Sync
 *
 * Converts a repo's `.mcp.json` into the per-backend formats Codex
 * (`.codex/config.toml`) and Gemini (`.gemini/settings.json`) expect.
 *
 * Lives in shared, not the CLI, because studios get created from two places —
 * `ink studio new` and the `create_studio` MCP tool — and both must bootstrap a
 * worktree identically. When only the CLI did this, agent-created studios
 * landed with no `.mcp.json` and no `.codex/config.toml`; Codex then spawned
 * against a partial `[mcp_servers.inkwell]` and died on "invalid transport",
 * while Claude sessions there simply had no MCP tools at all.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

export interface McpServerConfig {
  type?: string;
  url?: string;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  headers?: Record<string, string>;
  [key: string]: unknown;
}

export interface McpJson {
  mcpServers: Record<string, McpServerConfig>;
}
const CODEX_MANAGED_START = '# ink-managed:start mcp_servers';
const CODEX_MANAGED_END = '# ink-managed:end mcp_servers';
// Backward compat: detect old markers during replacement
const CODEX_MANAGED_START_LEGACY = '# pcp-managed:start mcp_servers';
const CODEX_MANAGED_END_LEGACY = '# pcp-managed:end mcp_servers';
// ============================================================================
// Env file parsing
// ============================================================================

/**
 * Parse a .env file into key-value pairs.
 * Handles comments, empty lines, quoted values, and inline comments.
 */
export function parseEnvFile(filePath: string): Record<string, string> {
  if (!existsSync(filePath)) return {};

  const vars: Record<string, string> = {};
  const content = readFileSync(filePath, 'utf-8');

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();

    // Strip surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    } else {
      // Strip inline comments for unquoted values
      const commentIdx = value.indexOf(' #');
      if (commentIdx !== -1) {
        value = value.slice(0, commentIdx).trim();
      }
    }

    if (key) vars[key] = value;
  }

  return vars;
}

/**
 * Scan a server config for ${VAR} template references.
 * Returns the set of variable names referenced.
 */
export function findTemplateVars(config: McpServerConfig): Set<string> {
  const vars = new Set<string>();
  const pattern = /\$\{(\w+)\}/g;

  function scan(val: unknown): void {
    if (typeof val === 'string') {
      for (const match of val.matchAll(pattern)) {
        vars.add(match[1]);
      }
    } else if (val && typeof val === 'object') {
      for (const v of Object.values(val)) {
        scan(v);
      }
    }
  }

  scan(config);
  return vars;
}

/**
 * Inject .env.local values into server configs for vars referenced via ${VAR} syntax.
 * Returns a new servers map with env vars injected — does not mutate the input.
 */
function injectEnvLocal(
  servers: Record<string, McpServerConfig>,
  envVars: Record<string, string>
): Record<string, McpServerConfig> {
  if (Object.keys(envVars).length === 0) return servers;

  const result: Record<string, McpServerConfig> = {};

  for (const [name, config] of Object.entries(servers)) {
    const referencedVars = findTemplateVars(config);
    const injected: Record<string, string> = {};

    for (const varName of referencedVars) {
      if (envVars[varName] && !config.env?.[varName]) {
        injected[varName] = envVars[varName];
      }
    }

    if (Object.keys(injected).length > 0) {
      result[name] = {
        ...config,
        env: { ...injected, ...config.env },
      };
    } else {
      result[name] = config;
    }
  }

  return result;
}

// ============================================================================
// Format converters
// ============================================================================

/**
 * Convert .mcp.json servers to Codex TOML format.
 * Only emits the [mcp_servers.*] sections.
 */
function toCodexToml(servers: Record<string, McpServerConfig>): string {
  const lines: string[] = [
    '# Generated by `ink mcp sync` from .mcp.json',
    '# Re-run `ink mcp sync` after changing .mcp.json',
    '',
  ];

  for (const [name, config] of Object.entries(servers)) {
    lines.push(`[mcp_servers.${name}]`);

    if (config.url) {
      lines.push(`url = ${tomlString(config.url)}`);
    }

    // Inkwell server: mark as required so Codex fails loudly if it can't connect
    if (name === 'inkwell') {
      lines.push('required = true');
    }

    if (config.command) {
      lines.push(`command = ${tomlString(config.command)}`);
    }

    if (config.args?.length) {
      lines.push(`args = [${config.args.map(tomlString).join(', ')}]`);
    }

    // Codex only supports `env` for stdio servers, not streamable_http (url-based)
    if (config.env && Object.keys(config.env).length > 0 && !config.url) {
      const pairs = Object.entries(config.env)
        .map(([k, v]) => `${tomlString(k)} = ${tomlString(v)}`)
        .join(', ');
      lines.push(`env = { ${pairs} }`);
    }

    if (config.headers) {
      // Detect "Authorization: Bearer ${ENV_VAR}" pattern → Codex bearer_token_env_var
      const authHeader = config.headers['Authorization'] || config.headers['authorization'];
      const bearerMatch = authHeader?.match(/^Bearer \$\{(\w+)\}$/);

      if (bearerMatch) {
        lines.push(`bearer_token_env_var = ${tomlString(bearerMatch[1])}`);
        // Emit remaining non-auth headers as http_headers if any
        const remaining = Object.entries(config.headers).filter(
          ([k]) => k.toLowerCase() !== 'authorization'
        );
        if (remaining.length > 0) {
          const pairs = remaining.map(([k, v]) => `${tomlString(k)} = ${tomlString(v)}`).join(', ');
          lines.push(`http_headers = { ${pairs} }`);
        }
      } else {
        const pairs = Object.entries(config.headers)
          .map(([k, v]) => `${tomlString(k)} = ${tomlString(v)}`)
          .join(', ');
        lines.push(`http_headers = { ${pairs} }`);
      }
    }

    lines.push('');
  }

  return lines.join('\n');
}

function renderCodexManagedBlock(servers: Record<string, McpServerConfig>): string {
  const body = toCodexToml(servers).trimEnd();
  return `${CODEX_MANAGED_START}\n${body}\n${CODEX_MANAGED_END}\n`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function isTomlSectionHeader(line: string): boolean {
  return /^\s*\[[^\]]+\]\s*$/.test(line);
}

function isMcpSectionHeader(line: string): boolean {
  return /^\s*\[mcp_servers(?:\.[^\]]+)?\]\s*$/.test(line);
}

function stripLegacyMcpSections(content: string): string {
  const lines = content.split('\n');
  const kept: string[] = [];

  let i = 0;
  while (i < lines.length) {
    if (!isMcpSectionHeader(lines[i])) {
      kept.push(lines[i]);
      i += 1;
      continue;
    }

    // Skip current MCP section until the next TOML section header
    i += 1;
    while (i < lines.length && !isTomlSectionHeader(lines[i])) {
      i += 1;
    }

    // Also skip blank lines directly after removed section to avoid extra gaps
    while (i < lines.length && lines[i].trim() === '') {
      i += 1;
    }

    if (kept.length > 0 && kept[kept.length - 1] !== '') {
      kept.push('');
    }
  }

  return kept.join('\n');
}

function stripLegacySyncHeaders(content: string): string {
  const filtered = content
    .split('\n')
    .filter(
      (line) =>
        line.trim() !== '# Generated by `ink mcp sync` from .mcp.json' &&
        line.trim() !== '# Re-run `ink mcp sync` after changing .mcp.json'
    );
  return filtered.join('\n');
}

function ensureTrailingNewline(content: string): string {
  return content.endsWith('\n') ? content : `${content}\n`;
}

function mergeCodexConfig(existing: string | undefined, managedBlock: string): string {
  if (!existing || existing.trim() === '') {
    return managedBlock;
  }

  // Detect current or legacy managed block markers
  const hasCurrentBlock =
    existing.includes(CODEX_MANAGED_START) && existing.includes(CODEX_MANAGED_END);
  const hasLegacyBlock =
    existing.includes(CODEX_MANAGED_START_LEGACY) && existing.includes(CODEX_MANAGED_END_LEGACY);

  if (hasCurrentBlock || hasLegacyBlock) {
    const startMarker = hasCurrentBlock ? CODEX_MANAGED_START : CODEX_MANAGED_START_LEGACY;
    const endMarker = hasCurrentBlock ? CODEX_MANAGED_END : CODEX_MANAGED_END_LEGACY;
    const pattern = new RegExp(
      `${escapeRegExp(startMarker)}[\\s\\S]*?${escapeRegExp(endMarker)}\\n?`,
      'm'
    );
    return ensureTrailingNewline(existing.replace(pattern, managedBlock));
  }

  // Back-compat: strip legacy generated MCP sections while preserving unrelated config (e.g. hooks)
  const cleaned = stripLegacySyncHeaders(stripLegacyMcpSections(existing)).trimEnd();
  if (!cleaned) {
    return managedBlock;
  }

  return ensureTrailingNewline(`${cleaned}\n\n${managedBlock}`);
}

function tomlString(val: string): string {
  return `"${val.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * Convert .mcp.json servers to Gemini settings.json format.
 * Merges into existing settings.json if present.
 */
function toGeminiSettings(
  servers: Record<string, McpServerConfig>,
  existingSettings?: Record<string, unknown>
): Record<string, unknown> {
  const geminiServers: Record<string, Record<string, unknown>> = {};

  for (const [name, config] of Object.entries(servers)) {
    const server: Record<string, unknown> = {};

    if (config.type) {
      server.type = config.type;
    }

    if (config.url) {
      server.url = config.url;
    }

    if (config.command) {
      server.command = config.command;
    }

    if (config.args?.length) {
      server.args = config.args;
    }

    if (config.env && Object.keys(config.env).length > 0) {
      server.env = config.env;
    }

    if (config.headers) {
      server.headers = config.headers;
    }

    geminiServers[name] = server;
  }

  return {
    ...existingSettings,
    mcpServers: geminiServers,
  };
}

// ============================================================================
// Gitignore helper
// ============================================================================

function ensureGitignoreEntries(repoRoot: string, entries: string[]): string[] {
  const gitignorePath = join(repoRoot, '.gitignore');
  const added: string[] = [];

  let content = '';
  if (existsSync(gitignorePath)) {
    content = readFileSync(gitignorePath, 'utf-8');
  }

  const lines = content.split('\n');
  const missing = entries.filter((entry) => !lines.some((line) => line.trim() === entry));

  if (missing.length > 0) {
    const suffix = content.endsWith('\n') ? '' : '\n';
    const block = `${suffix}\n# Backend-specific config (generated by ink mcp sync)\n${missing.join('\n')}\n`;
    writeFileSync(gitignorePath, content + block);
    added.push(...missing);
  }

  return added;
}

/**
 * Core sync logic: read .mcp.json from targetDir and write .codex/ and .gemini/ configs.
 */
export function syncMcpConfig(
  targetDir: string,
  options?: { sourceMcpPath?: string; sourceEnvPath?: string }
): { codex: boolean; gemini: boolean } {
  const mcpPath = options?.sourceMcpPath || join(targetDir, '.mcp.json');

  if (!existsSync(mcpPath)) {
    return { codex: false, gemini: false };
  }

  let mcpJson: McpJson;
  try {
    mcpJson = JSON.parse(readFileSync(mcpPath, 'utf-8'));
  } catch {
    return { codex: false, gemini: false };
  }

  if (!mcpJson.mcpServers || Object.keys(mcpJson.mcpServers).length === 0) {
    return { codex: false, gemini: false };
  }

  // --- Resolve env vars from .env.local ---
  const sourceEnv = options?.sourceEnvPath ? parseEnvFile(options.sourceEnvPath) : {};
  const targetEnv = parseEnvFile(join(targetDir, '.env.local'));
  const envLocal = { ...sourceEnv, ...targetEnv };
  const servers = injectEnvLocal(mcpJson.mcpServers, envLocal);

  // --- Codex: .codex/config.toml ---
  const codexDir = join(targetDir, '.codex');
  const codexPath = join(codexDir, 'config.toml');
  mkdirSync(codexDir, { recursive: true });
  const existingCodex = existsSync(codexPath) ? readFileSync(codexPath, 'utf-8') : undefined;
  const managedBlock = renderCodexManagedBlock(servers);
  writeFileSync(codexPath, mergeCodexConfig(existingCodex, managedBlock));

  // --- Gemini: .gemini/settings.json ---
  const geminiDir = join(targetDir, '.gemini');
  const geminiPath = join(geminiDir, 'settings.json');
  mkdirSync(geminiDir, { recursive: true });

  let existingGemini: Record<string, unknown> | undefined;
  if (existsSync(geminiPath)) {
    try {
      existingGemini = JSON.parse(readFileSync(geminiPath, 'utf-8'));
    } catch {
      /* overwrite if unparseable */
    }
  }

  const geminiSettings = toGeminiSettings(servers, existingGemini);
  writeFileSync(geminiPath, JSON.stringify(geminiSettings, null, 2) + '\n');

  // --- Gitignore ---
  ensureGitignoreEntries(targetDir, ['.codex/', '.gemini/']);

  return { codex: true, gemini: true };
}
