import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { syncMcpConfig, tomlTableHeaders } from './mcp-config-sync.js';

let root: string;
beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'mcp-config-sync-'));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

const mcpJson = {
  mcpServers: {
    figma: { type: 'http', url: 'https://mcp.example.com/figma' },
    inkwell: { type: 'http', url: 'http://localhost:3001/mcp' },
  },
};

function studio(codexToml?: string): string {
  writeFileSync(join(root, '.mcp.json'), JSON.stringify(mcpJson));
  if (codexToml !== undefined) {
    mkdirSync(join(root, '.codex'));
    writeFileSync(join(root, '.codex', 'config.toml'), codexToml);
  }
  return join(root, '.codex', 'config.toml');
}

describe('syncMcpConfig, a server declared outside the managed block', () => {
  // The shape found in lumen-alpha on 2026-09-29 (#701): a legacy header,
  // hooks, the managed block holding figma, and figma again outside it.
  // Codex refused to parse it (duplicate key), so every spawn there failed.
  const broken = [
    '# Generated by `sb config sync` from .mcp.json',
    '',
    '',
    '[hooks]',
    'synthetic = "hook"',
    '# ink-managed:hooks:end',
    '',
    '# ink-managed:start mcp_servers',
    '# Generated by `ink mcp sync` from .mcp.json',
    '',
    '[mcp_servers.figma]',
    'url = "https://mcp.example.com/figma"',
    '',
    '[mcp_servers.inkwell]',
    'url = "http://localhost:3001/mcp"',
    '# ink-managed:end mcp_servers',
    '',
    '[mcp_servers.figma]',
    'url = "https://mcp.example.com/figma"',
    '',
  ].join('\n');

  it('repairs the duplicate: the block leaves figma to the declaration outside it', () => {
    const codexPath = studio(broken);
    const result = syncMcpConfig(root);
    const tables = tomlTableHeaders(readFileSync(codexPath, 'utf-8'));
    expect(tables.filter((t) => t === 'mcp_servers.figma')).toHaveLength(1);
    expect(tables.filter((t) => t === 'mcp_servers.inkwell')).toHaveLength(1);
    expect(result.codexKeptOutside).toEqual(['figma']);
    // The outside declaration and the hooks are untouched.
    expect(readFileSync(codexPath, 'utf-8')).toContain('[hooks]\nsynthetic = "hook"');
  });

  it('leaves a clean file with each server declared once, and a second sync changes nothing', () => {
    const codexPath = studio(broken);
    syncMcpConfig(root);
    const once = readFileSync(codexPath, 'utf-8');
    syncMcpConfig(root);
    expect(readFileSync(codexPath, 'utf-8')).toBe(once);
    const tables = tomlTableHeaders(once);
    expect(new Set(tables).size).toBe(tables.length);
  });

  it('keeps every server in the block when none is declared outside (control)', () => {
    const codexPath = studio();
    const result = syncMcpConfig(root);
    const text = readFileSync(codexPath, 'utf-8');
    expect(tomlTableHeaders(text)).toEqual(['mcp_servers.figma', 'mcp_servers.inkwell']);
    // Reported only when something was kept outside.
    expect(result).toEqual({ codex: true, gemini: true });
  });
});

describe('tomlTableHeaders', () => {
  it('normalizes quotes and spacing, and leaves out arrays of tables', () => {
    expect(
      tomlTableHeaders(
        [
          '[ mcp_servers . "figma" ]  # a comment',
          "[mcp_servers.'inkwell']",
          '[[profiles]]',
          'key = "[not.a.table]"',
          '  [hooks]',
        ].join('\n')
      )
    ).toEqual(['mcp_servers.figma', 'mcp_servers.inkwell', 'hooks']);
  });
});
